"""added book slug

Revision ID: 058025e48aa6
Revises: 
Create Date: 2026-07-12 19:43:52.057898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058025e48aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('audience', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sold', sa.Integer(), nullable=True))
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('authors',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_foreign_key(None, 'staff', ['deleted_by'], ['id'])

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=600),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('temp_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('checkout_request_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=40),
               existing_nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deactivated_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('tkv',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=12),
               nullable=True)
        batch_op.create_foreign_key(None, 'staff', ['deactivated_by'], ['id'])
        batch_op.create_foreign_key(None, 'staff', ['edited_by'], ['id'])

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('institution_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('conversation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('challenges', sa.Text(), nullable=True))
        batch_op.alter_column('staffName',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('saleComments',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])
        batch_op.drop_column('visitLocation')
        batch_op.drop_column('locationPhone')
        batch_op.drop_column('locationEmail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locationEmail', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('locationPhone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('visitLocation', sa.VARCHAR(length=1024), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('saleComments',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('staffName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('challenges')
        batch_op.drop_column('conversation_notes')
        batch_op.drop_column('category')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('institution_name')
        batch_op.drop_column('staff_id')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tkv',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('deactivated_by')
        batch_op.drop_column('edited_by')
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('checkout_request_id',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('temp_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('endpoint',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('authors',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('sold')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('audience')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
